# -*- coding: utf-8 -*-
"""Detective stories, part four."""

STORIES = [
{
 "id": "llaves",
 "title": "Las llaves equivocadas",
 "blurb": "A set of keys returned to a widow, with one key too many.",
 "paragraphs": [
  [
   ["Gonzalo Ibarra murió en su oficina un viernes de noviembre, poco después de las ocho de la noche.", "Gonzalo Ibarra morì nel suo ufficio un venerdì di novembre, poco dopo le otto di sera."],
   ["Era contador y tenía un despacho pequeño en un edificio de oficinas de la colonia Juárez.", "Era commercialista e aveva uno studio piccolo in un palazzo di uffici della colonia Juárez."],
   ["El velador lo encontró a las once, cuando hizo su segunda ronda del turno.", "Il guardiano lo trovò alle undici, quando fece il secondo giro del turno."],
   ["La puerta del despacho estaba cerrada y no había señales de que la hubieran forzado.", "La porta dello studio era chiusa e non c'erano segni di scasso."],
   ["Elena Vargas llegó cuando ya se habían llevado el cuerpo, que era como prefería llegar.", "Elena Vargas arrivò quando avevano già portato via il corpo, che era come preferiva arrivare."],
  ],
  [
   ["El velador entregó las llaves de Ibarra a la viuda el sábado por la mañana.", "Il guardiano consegnò le chiavi di Ibarra alla vedova il sabato mattina."],
   ["Era un llavero de cuero gastado, con una argolla grande y varias llaves.", "Era un portachiavi di cuoio consumato, con un anello grande e varie chiavi."],
   ["La viuda se llamaba Amparo y las contó dos veces antes de decir nada.", "La vedova si chiamava Amparo e le contò due volte prima di dire niente."],
   ["Después llamó a la policía y pidió hablar con alguien que la tomara en serio.", "Poi chiamò la polizia e chiese di parlare con qualcuno che la prendesse sul serio."],
   ["Elena fue a verla esa misma tarde, y esa fue toda la investigación que hizo falta.", "Elena andò a trovarla quel pomeriggio stesso, e quella fu tutta l'indagine che servì."],
  ],
  [
   ["—Son siete llaves —dijo Amparo, poniéndolas sobre la mesa de la cocina—.", "«Sono sette chiavi», disse Amparo, mettendole sul tavolo della cucina."],
   ["—Mi marido tenía seis. Las conozco todas.", "«Mio marito ne aveva sei. Le conosco tutte»."],
   ["Señaló cada una despacio, como quien reza.", "Indicò ognuna lentamente, come chi prega."],
   ["—Casa, oficina, archivo, coche, casa de su madre, y la del portón de allá abajo.", "«Casa, ufficio, archivio, macchina, casa di sua madre, e quella del portone giù»."],
   ["—Esta séptima no la había visto en mi vida.", "«Questa settima non l'avevo mai vista in vita mia»."],
  ],
  [
   ["Elena tomó la llave desconocida y la puso contra la luz de la ventana.", "Elena prese la chiave sconosciuta e la mise controluce alla finestra."],
   ["Era nueva, de latón, con los dientes limpios y sin el brillo gastado de las otras.", "Era nuova, di ottone, con i denti puliti e senza il lucido consumato delle altre."],
   ["Una llave usada se opaca y se raya; esta parecía recién salida del cerrajero.", "Una chiave usata si opacizza e si graffia; questa sembrava appena uscita dal fabbro."],
   ["Y el llavero era de argolla cerrada, de esos que cuesta trabajo abrir con las uñas.", "E il portachiavi era ad anello chiuso, di quelli che si aprono a fatica con le unghie."],
   ["Nadie le agrega una llave a un llavero así por accidente.", "Nessuno aggiunge una chiave a un portachiavi così per sbaglio."],
  ],
  [
   ["El velador se llamaba Prudencio y llevaba nueve años en el edificio.", "Il guardiano si chiamava Prudencio e lavorava da nove anni nel palazzo."],
   ["Cuando Elena le preguntó por la séptima llave, dijo que él no había tocado nada.", "Quando Elena gli chiese della settima chiave, disse che lui non aveva toccato niente."],
   ["Cuando le preguntó de dónde había sacado la llave de su propia casa, se quedó callado.", "Quando gli chiese da dove avesse preso la chiave di casa sua, rimase zitto."],
   ["Elena no había dicho que la llave fuera de su casa.", "Elena non aveva detto che la chiave fosse di casa sua."],
   ["Lo dijo él, con el silencio, que es la manera más lenta de confesar.", "Lo disse lui, con il silenzio, che è il modo più lento di confessare."],
  ],
  [
   ["Había entrado a robar, y no contaba con que Ibarra siguiera trabajando tan tarde.", "Era entrato per rubare, e non si aspettava che Ibarra lavorasse ancora così tardi."],
   ["Después quiso devolver el llavero completo y se equivocó al armarlo de vuelta.", "Poi volle restituire il portachiavi completo e sbagliò a rimetterlo insieme."],
   ["Puso todas las llaves, incluida la suya, que llevaba en el mismo bolsillo.", "Mise tutte le chiavi, compresa la sua, che teneva nella stessa tasca."],
   ["—La gente se delata por exceso de cuidado —le dijo Elena a Beltrán esa noche.", "«La gente si tradisce per eccesso di attenzione», disse Elena a Beltrán quella sera."],
   ["—Los descuidados dejan huellas. Los cuidadosos dejan una llave de más.", "«I distratti lasciano impronte. I meticolosi lasciano una chiave in più»."],
  ],
 ],
},
{
 "id": "boleto",
 "title": "El boleto de autobús",
 "blurb": "An alibi printed on paper, with the wrong number of passengers on it.",
 "paragraphs": [
  [
   ["A Rosalía Menchaca la mataron en su casa de Puebla un domingo por la mañana.", "Rosalía Menchaca fu uccisa in casa sua a Puebla una domenica mattina."],
   ["El caso no era de Elena, pero el principal sospechoso vivía en la Ciudad de México.", "Il caso non era di Elena, ma il principale sospettato viveva a Città del Messico."],
   ["Se llamaba Fabián Rueda, era su primo, y heredaba la casa y un terreno.", "Si chiamava Fabián Rueda, era suo cugino, ed ereditava la casa e un terreno."],
   ["Elena lo recibió en su oficina un martes, con la ventana abierta y mucho ruido de la calle.", "Elena lo ricevette nel suo ufficio un martedì, con la finestra aperta e molto rumore dalla strada."],
   ["El hombre traía su coartada en la mano, doblada en cuatro.", "L'uomo portava il suo alibi in mano, piegato in quattro."],
  ],
  [
   ["Era un boleto de autobús de México a Puebla, con fecha del lunes.", "Era un biglietto dell'autobus da Città del Messico a Puebla, con data lunedì."],
   ["—Yo llegué el lunes —dijo—. Ella ya llevaba un día muerta.", "«Io sono arrivato lunedì», disse. «Lei era già morta da un giorno»."],
   ["El boleto tenía hora, asiento, andén y el nombre de la línea impreso arriba.", "Il biglietto aveva ora, posto, binario e il nome della compagnia stampato sopra."],
   ["Elena lo leyó dos veces y después lo dejó sobre el escritorio sin devolvérselo.", "Elena lo lesse due volte e poi lo posò sulla scrivania senza restituirglielo."],
   ["—Muy bien guardado para un boleto de un viaje sin importancia —dijo.", "«Molto ben conservato per un biglietto di un viaggio senza importanza», disse."],
  ],
  [
   ["Fabián explicó que él guardaba todo, que era ordenado, que su madre le había enseñado así.", "Fabián spiegò che lui conservava tutto, che era ordinato, che sua madre gli aveva insegnato così."],
   ["Elena asintió y le preguntó si el autobús iba lleno.", "Elena annuì e gli chiese se l'autobus fosse pieno."],
   ["Él dijo que sí, bastante lleno, y que había tenido que ir junto a la ventana.", "Lui disse di sì, abbastanza pieno, e che aveva dovuto stare vicino al finestrino."],
   ["Elena marcó el número de la terminal y preguntó por la corrida de ese lunes.", "Elena chiamò il numero della stazione e chiese della corsa di quel lunedì."],
   ["Le confirmaron el horario, el andén y el número de pasajeros que habían subido.", "Le confermarono l'orario, il binario e il numero di passeggeri che erano saliti."],
   ["Once personas, en un autobús de cuarenta y ocho asientos.", "Undici persone, su un autobus di quarantotto posti."],
  ],
  [
   ["—Once —repitió Elena, con el teléfono todavía en la mano.", "«Undici», ripeté Elena, con il telefono ancora in mano."],
   ["—Once no es bastante lleno. Once es un autobús vacío.", "«Undici non è abbastanza pieno. Undici è un autobus vuoto»."],
   ["—Con once personas uno se sienta donde quiere, y nadie tiene que ir junto a nadie.", "«Con undici persone ci si siede dove si vuole, e nessuno deve stare accanto a nessuno»."],
   ["Fabián dijo que quizá se confundía de viaje, que hacía ese trayecto seguido.", "Fabián disse che forse confondeva il viaggio, che faceva quel tragitto spesso."],
   ["Fue una respuesta razonable, y por eso mismo fue la peor que pudo dar.", "Fu una risposta ragionevole, e proprio per questo fu la peggiore che potesse dare."],
  ],
  [
   ["Si hacía ese trayecto seguido, tenía boletos de muchos lunes y de muchos domingos.", "Se faceva quel tragitto spesso, aveva biglietti di molti lunedì e di molte domeniche."],
   ["Elena pidió una orden y encontró catorce boletos guardados en una caja de zapatos.", "Elena chiese un mandato e trovò quattordici biglietti conservati in una scatola da scarpe."],
   ["Uno de ellos era del domingo, comprado a las seis de la mañana, sin usar el regreso.", "Uno di essi era della domenica, comprato alle sei del mattino, con il ritorno non usato."],
   ["Había comprado el del lunes para enseñarlo y había guardado el del domingo por costumbre.", "Aveva comprato quello del lunedì per mostrarlo e aveva conservato quello della domenica per abitudine."],
   ["Su madre le había enseñado a guardarlo todo, y esa fue exactamente su ruina.", "Sua madre gli aveva insegnato a conservare tutto, e quella fu esattamente la sua rovina."],
  ],
 ],
},
{
 "id": "voz",
 "title": "La voz en el teléfono",
 "blurb": "A call for help at nine, from a woman who had already been dead for hours.",
 "paragraphs": [
  [
   ["La denuncia entró a las nueve y cuatro minutos de la noche de un miércoles.", "La denuncia arrivò alle nove e quattro minuti di sera di un mercoledì."],
   ["Una voz de mujer pidió ayuda, dio una dirección de la colonia Del Valle y colgó.", "Una voce di donna chiese aiuto, diede un indirizzo della colonia Del Valle e riattaccò."],
   ["La patrulla llegó doce minutos después y encontró la puerta entreabierta.", "La volante arrivò dodici minuti dopo e trovò la porta socchiusa."],
   ["Adentro, en la sala, estaba el cuerpo de la señora Julia Bermúdez, de cincuenta y ocho años.", "Dentro, in salotto, c'era il corpo della signora Julia Bermúdez, di cinquantotto anni."],
   ["El forense fue claro y no dejó lugar a discusión sobre la hora.", "Il medico legale fu chiaro e non lasciò spazio a discussioni sull'ora."],
   ["La mujer llevaba muerta desde las cuatro de la tarde, cinco horas antes de la llamada.", "La donna era morta dalle quattro del pomeriggio, cinque ore prima della chiamata."],
  ],
  [
   ["Elena Vargas escuchó la grabación seis veces seguidas, sentada y sin moverse.", "Elena Vargas ascoltò la registrazione sei volte di seguito, seduta e senza muoversi."],
   ["La voz decía: «Ayúdenme, por favor, en Amores 148, departamento tres».", "La voce diceva: «Aiutatemi, per favore, in Amores 148, appartamento tre»."],
   ["Después había un ruido corto y la línea se cortaba.", "Poi c'era un rumore corto e la linea si interrompeva."],
   ["El yerno de la señora identificó la voz sin dudarlo ni un segundo.", "Il genero della signora riconobbe la voce senza esitare un secondo."],
   ["—Es ella —dijo—. Es la voz de Julia. La conozco desde hace veinte años.", "«È lei», disse. «È la voce di Julia. La conosco da vent'anni»."],
  ],
  [
   ["Elena volvió a escuchar la grabación, esta vez con los ojos cerrados.", "Elena riascoltò la registrazione, questa volta a occhi chiusi."],
   ["La voz era clara, sin miedo, sin aire, sin ese temblor de la gente que suplica.", "La voce era chiara, senza paura, senza fiato, senza quel tremore della gente che supplica."],
   ["Decía la dirección completa, con número de departamento, como se dicta un dato.", "Diceva l'indirizzo completo, con numero di appartamento, come si detta un dato."],
   ["Nadie que se está muriendo recita su dirección como si llenara un formulario.", "Nessuno che sta morendo recita il proprio indirizzo come se compilasse un modulo."],
   ["Y detrás de la voz no había nada: ni calle, ni televisión, ni refrigerador.", "E dietro la voce non c'era niente: né strada, né televisione, né frigorifero."],
   ["Un departamento en Del Valle a las nueve de la noche nunca está tan callado.", "Un appartamento a Del Valle alle nove di sera non è mai così silenzioso."],
  ],
  [
   ["Elena preguntó si la señora tenía contestadora, y el yerno dijo que sí, una vieja.", "Elena chiese se la signora avesse una segreteria telefonica, e il genero disse di sì, vecchia."],
   ["Preguntó si alguna vez había grabado su propio saludo, y él dijo que claro.", "Chiese se avesse mai registrato il proprio messaggio, e lui disse certo."],
   ["Fueron al departamento y encontraron la contestadora desconectada sobre el mueble.", "Andarono all'appartamento e trovarono la segreteria staccata sul mobile."],
   ["El cassette no estaba.", "La cassetta non c'era."],
   ["Elena miró el enchufe suelto y entendió el resto sin necesidad de decirlo.", "Elena guardò la spina staccata e capì il resto senza bisogno di dirlo."],
  ],
  [
   ["Alguien había grabado a Julia diciendo su dirección, quizá pidiéndoselo con cualquier pretexto.", "Qualcuno aveva registrato Julia mentre diceva il suo indirizzo, magari chiedendoglielo con un pretesto qualsiasi."],
   ["Después la mató a las cuatro y se fue a cenar a un lugar con testigos.", "Poi la uccise alle quattro e andò a cena in un posto con testimoni."],
   ["A las nueve puso la grabación frente al teléfono y colgó desde otra parte de la ciudad.", "Alle nove mise la registrazione davanti al telefono e riattaccò da un'altra parte della città."],
   ["La coartada era perfecta, salvo por una cosa que no se puede grabar.", "L'alibi era perfetto, tranne per una cosa che non si può registrare."],
   ["El miedo.", "La paura."],
  ],
 ],
},
]
