# -*- coding: utf-8 -*-
"""Detective stories, part one.

Inspectora Elena Vargas, Mexico City. Each case is self-contained and turns on
one observed detail, in the Holmes manner.

Spanish is Latin American and deliberately plain: past narration uses the
preterite throughout, which is both what Mexico says and what the rest of the
app teaches. Every sentence carries its own Italian, translated to match the
register rather than word for word.
"""

STORIES = [
{
 "id": "reloj",
 "title": "El reloj detenido",
 "blurb": "A clock stopped at 3:15, and the only man who could have stopped it.",
 "paragraphs": [
  [
   ["La llamada llegó a las seis de la mañana.", "La chiamata arrivò alle sei del mattino."],
   ["Elena Vargas ya estaba despierta.", "Elena Vargas era già sveglia."],
   ["Nunca dormía bien en octubre.", "Non dormiva mai bene in ottobre."],
   ["El agente Beltrán la esperaba en la puerta del edificio.", "L'agente Beltrán la aspettava alla porta del palazzo."],
   ["—Cuarto piso —dijo—. El portero encontró el cuerpo.", "«Quarto piano», disse. «Il portiere ha trovato il corpo»."],
  ],
  [
   ["El edificio era viejo y olía a humedad y a cera de piso.", "Il palazzo era vecchio e sapeva di umidità e di cera per pavimenti."],
   ["En la escalera, una mujer barría el mismo escalón desde hacía rato.", "Sulle scale, una donna spazzava lo stesso gradino già da un pezzo."],
   ["Elena la saludó y la mujer bajó los ojos.", "Elena la salutò e la donna abbassò gli occhi."],
   ["En este país la gente sabe más de lo que dice.", "In questo paese la gente sa più di quanto dica."],
   ["El truco está en esperar sin apurarla.", "Il trucco sta nell'aspettare senza metterle fretta."],
  ],
  [
   ["El departamento era pequeño y estaba muy ordenado.", "L'appartamento era piccolo e molto ordinato."],
   ["Ricardo Nava tenía sesenta años y vivía solo.", "Ricardo Nava aveva sessant'anni e viveva da solo."],
   ["Estaba en el suelo, cerca de la ventana.", "Era per terra, vicino alla finestra."],
   ["A su lado había un reloj de mesa, caído.", "Accanto a lui c'era un orologio da tavolo, caduto."],
   ["El reloj marcaba las tres y cuarto.", "L'orologio segnava le tre e un quarto."],
   ["—Se detuvo cuando cayó —dijo Beltrán—. Tres y cuarto de la madrugada.", "«Si è fermato quando è caduto», disse Beltrán. «Le tre e un quarto di notte»."],
   ["Elena no respondió.", "Elena non rispose."],
   ["Se puso de rodillas y miró el reloj sin tocarlo.", "Si mise in ginocchio e guardò l'orologio senza toccarlo."],
  ],
  [
   ["El sobrino llegó media hora después.", "Il nipote arrivò mezz'ora dopo."],
   ["Se llamaba Tomás y trabajaba en un banco.", "Si chiamava Tomás e lavorava in una banca."],
   ["Tenía los ojos rojos y las manos tranquilas.", "Aveva gli occhi rossi e le mani tranquille."],
   ["—Cené con él anoche —dijo—. Me fui a las once.", "«Ho cenato con lui ieri sera», disse. «Sono andato via alle undici»."],
   ["—¿Y después? —preguntó Elena.", "«E poi?», chiese Elena."],
   ["—Fui a mi casa. Vivo en Coyoacán.", "«Sono andato a casa. Abito a Coyoacán»."],
   ["—¿Alguien lo vio llegar?", "«Qualcuno l'ha visto arrivare?»"],
   ["—Vivo solo, inspectora.", "«Vivo da solo, ispettrice»."],
  ],
  [
   ["Elena dejó al sobrino con Beltrán y recorrió el departamento sola.", "Elena lasciò il nipote con Beltrán e girò l'appartamento da sola."],
   ["Le gustaba mirar las casas de los muertos sin nadie hablándole al oído.", "Le piaceva guardare le case dei morti senza nessuno che le parlasse all'orecchio."],
   ["Una casa dice cosas que los parientes prefieren callar.", "Una casa dice cose che i parenti preferiscono tacere."],
   ["Había libros de historia en el buró, con separadores de papel.", "C'erano libri di storia sul comodino, con segnalibri di carta."],
   ["Había una cama tendida con las esquinas bien metidas.", "C'era un letto rifatto con gli angoli ben rimboccati."],
   ["Un hombre así no deja un reloj tirado en el suelo.", "Un uomo così non lascia un orologio buttato per terra."],
  ],
  [
   ["Elena caminó hasta la cocina.", "Elena andò fino alla cucina."],
   ["Había dos platos limpios en el escurridor.", "C'erano due piatti puliti nello scolapiatti."],
   ["Dos vasos, dos tenedores, dos cuchillos.", "Due bicchieri, due forchette, due coltelli."],
   ["Todo estaba seco.", "Era tutto asciutto."],
   ["Volvió a la sala y levantó el reloj con un pañuelo.", "Tornò in salotto e sollevò l'orologio con un fazzoletto."],
   ["Le dio vuelta y miró la parte de atrás.", "Lo girò e guardò il retro."],
   ["—Beltrán —dijo—, este reloj es de cuerda.", "«Beltrán», disse, «questo orologio è a carica»."],
  ],
  [
   ["—¿Y eso qué importa? —preguntó el agente.", "«E questo che importa?», chiese l'agente."],
   ["—Importa mucho.", "«Importa molto»."],
   ["—Un reloj de cuerda se detiene solo cuando se le acaba la cuerda.", "«Un orologio a carica si ferma solo quando finisce la carica»."],
   ["—No se detiene por una caída.", "«Non si ferma per una caduta»."],
   ["Elena señaló la mesa.", "Elena indicò il tavolo."],
   ["—Alguien lo movió y lo puso en el suelo.", "«Qualcuno l'ha spostato e l'ha messo per terra»."],
   ["—Alguien quería que viéramos esa hora.", "«Qualcuno voleva che vedessimo quell'ora»."],
  ],
  [
   ["Tomás seguía en la puerta.", "Tomás era ancora sulla porta."],
   ["No se había movido en diez minutos.", "Non si era mosso da dieci minuti."],
   ["—Usted lavó los platos —dijo Elena.", "«Lei ha lavato i piatti», disse Elena."],
   ["—Están secos. Eso toma horas.", "«Sono asciutti. Ci vogliono ore»."],
   ["—Su tío murió antes de las once, no a las tres.", "«Suo zio è morto prima delle undici, non alle tre»."],
   ["—Usted se quedó, limpió, y adelantó el reloj.", "«Lei è rimasto, ha pulito e ha spostato avanti l'orologio»."],
   ["El hombre no dijo nada.", "L'uomo non disse niente."],
   ["Miró sus manos tranquilas y entendió que ya era tarde.", "Guardò le sue mani tranquille e capì che era ormai tardi."],
  ],
  [
   ["Beltrán lo esposó sin hacer ruido.", "Beltrán lo ammanettò senza far rumore."],
   ["Elena bajó las escaleras despacio.", "Elena scese le scale lentamente."],
   ["Afuera empezaba a llover.", "Fuori cominciava a piovere."],
   ["—¿Cómo lo supo? —preguntó el agente.", "«Come l'ha capito?», chiese l'agente."],
   ["—Nadie lava los platos después de matar a alguien —dijo ella—.", "«Nessuno lava i piatti dopo aver ucciso qualcuno», disse lei."],
   ["—A menos que quiera parecer un sobrino que cenó y se fue.", "«A meno che non voglia sembrare un nipote che ha cenato ed è andato via»."],
  ],
 ],
},
{
 "id": "carta",
 "title": "La carta sin sello",
 "blurb": "A letter that arrived by post, except that it never did.",
 "paragraphs": [
  [
   ["La librería estaba cerrada desde el jueves.", "La libreria era chiusa dal giovedì."],
   ["El dueño, don Isidro, tenía setenta y dos años.", "Il proprietario, don Isidro, aveva settantadue anni."],
   ["Lo encontraron el sábado, sentado en su silla.", "Lo trovarono il sabato, seduto sulla sua sedia."],
   ["El médico habló de un infarto.", "Il medico parlò di un infarto."],
   ["Elena Vargas no habría venido por un infarto.", "Elena Vargas non sarebbe venuta per un infarto."],
   ["Vino por la carta.", "Venne per la lettera."],
  ],
  [
   ["La librería era angosta y larga, como un pasillo con techo.", "La libreria era stretta e lunga, come un corridoio con il tetto."],
   ["Los libreros llegaban hasta el techo y se inclinaban un poco hacia adentro.", "Gli scaffali arrivavano fino al soffitto e si inclinavano un po' verso l'interno."],
   ["Olía a papel viejo, que es un olor dulce y triste.", "Sapeva di carta vecchia, che è un odore dolce e triste."],
   ["Don Isidro había vendido libros ahí durante cuarenta años.", "Don Isidro aveva venduto libri lì per quarant'anni."],
   ["Elena había comprado su primer diccionario en ese mostrador.", "Elena aveva comprato il suo primo dizionario su quel bancone."],
   ["No se lo dijo a nadie.", "Non lo disse a nessuno."],
  ],
  [
   ["Estaba sobre el mostrador, abierta.", "Era sul bancone, aperta."],
   ["La letra era grande y temblorosa.", "La calligrafia era grande e tremolante."],
   ["Decía que don Isidro dejaba la librería a su socio.", "Diceva che don Isidro lasciava la libreria al suo socio."],
   ["Estaba firmada y fechada el miércoles.", "Era firmata e datata mercoledì."],
   ["El socio se llamaba Aurelio Paz.", "Il socio si chiamava Aurelio Paz."],
   ["Llegó a la una de la tarde, muy serio.", "Arrivò all'una del pomeriggio, molto serio."],
   ["—Me la mandó por correo —dijo—. Llegó el viernes.", "«Me l'ha mandata per posta», disse. «È arrivata venerdì»."],
  ],
  [
   ["Elena tomó el sobre y lo miró contra la luz.", "Elena prese la busta e la guardò controluce."],
   ["Tenía el nombre de Aurelio escrito a mano.", "Aveva il nome di Aurelio scritto a mano."],
   ["No tenía sello.", "Non aveva francobollo."],
   ["No tenía matasellos.", "Non aveva timbro postale."],
   ["No tenía dirección.", "Non aveva indirizzo."],
   ["—Qué correo tan discreto —dijo ella.", "«Che posta discreta», disse lei."],
  ],
  [
   ["Aurelio explicó que el sobre venía dentro de otro.", "Aurelio spiegò che la busta era dentro un'altra."],
   ["Elena preguntó dónde estaba ese otro sobre.", "Elena chiese dove fosse quell'altra busta."],
   ["Aurelio dijo que lo había tirado.", "Aurelio disse che l'aveva buttata."],
   ["Ella asintió y no discutió.", "Lei annuì e non discusse."],
   ["Caminó entre los libreros, leyendo lomos.", "Camminò tra gli scaffali, leggendo i dorsi."],
   ["Se detuvo en la sección de poesía.", "Si fermò nella sezione di poesia."],
  ],
  [
   ["Había polvo en todas las repisas.", "C'era polvere su tutti i ripiani."],
   ["En una sola había una línea limpia.", "Su uno solo c'era una riga pulita."],
   ["Del ancho de un libro, más o menos.", "Della larghezza di un libro, più o meno."],
   ["—¿Falta algo aquí? —preguntó.", "«Manca qualcosa qui?», chiese."],
   ["—No que yo sepa —dijo Aurelio.", "«Non che io sappia», disse Aurelio."],
   ["Elena miró el suelo debajo de la repisa.", "Elena guardò il pavimento sotto il ripiano."],
   ["Había una hoja doblada, medio escondida.", "C'era un foglio piegato, mezzo nascosto."],
  ],
  [
   ["Elena se agachó y la recogió con dos dedos.", "Elena si chinò e lo raccolse con due dita."],
   ["El papel estaba frío y un poco húmedo por el suelo.", "La carta era fredda e un po' umida per via del pavimento."],
   ["Aurelio dio un paso hacia ella y después se detuvo.", "Aurelio fece un passo verso di lei e poi si fermò."],
   ["Ese paso valía más que todo lo que había dicho en una hora.", "Quel passo valeva più di tutto quello che aveva detto in un'ora."],
  ],
  [
   ["Era otra carta, con la misma letra temblorosa.", "Era un'altra lettera, con la stessa calligrafia tremolante."],
   ["Decía algo muy distinto.", "Diceva qualcosa di molto diverso."],
   ["Decía que don Isidro quería vender su parte y separarse de Aurelio.", "Diceva che don Isidro voleva vendere la sua parte e separarsi da Aurelio."],
   ["Estaba fechada el martes.", "Era datata martedì."],
   ["—Un día antes —dijo Elena—. Qué rápido cambió de opinión.", "«Un giorno prima», disse Elena. «Che rapido cambio d'idea»."],
  ],
  [
   ["Aurelio empezó a hablar y ella levantó una mano.", "Aurelio cominciò a parlare e lei alzò una mano."],
   ["—Usted estuvo aquí el miércoles —dijo—.", "«Lei è stato qui mercoledì», disse."],
   ["—Le dictó una carta a un hombre de setenta y dos años.", "«Ha dettato una lettera a un uomo di settantadue anni»."],
   ["—Y cuando salió, la dejó en el mostrador.", "«E quando è uscito, l'ha lasciata sul bancone»."],
   ["—Nunca pasó por el correo porque usted nunca la mandó.", "«Non è mai passata dalla posta perché lei non l'ha mai spedita»."],
   ["Afuera, un camión pasó despacio.", "Fuori, un camion passò lentamente."],
   ["Adentro nadie dijo nada durante mucho tiempo.", "Dentro nessuno disse niente per molto tempo."],
  ],
 ],
},
{
 "id": "cafe",
 "title": "El café frío",
 "blurb": "Two cups on the table, and only one of them still warm.",
 "paragraphs": [
  [
   ["El restaurante abría a la una.", "Il ristorante apriva all'una."],
   ["La cocinera llegó a las once y encontró la puerta abierta.", "La cuoca arrivò alle undici e trovò la porta aperta."],
   ["El gerente estaba en su oficina, con la cabeza sobre el escritorio.", "Il direttore era nel suo ufficio, con la testa sulla scrivania."],
   ["Elena Vargas llegó veinte minutos después.", "Elena Vargas arrivò venti minuti dopo."],
   ["Beltrán ya había hablado con la cocinera.", "Beltrán aveva già parlato con la cuoca."],
  ],
  [
   ["La oficina era un cuarto sin ventanas, detrás de la cocina.", "L'ufficio era una stanza senza finestre, dietro la cucina."],
   ["Había facturas en una pila y un ventilador apagado.", "C'erano fatture in una pila e un ventilatore spento."],
   ["El aire estaba pesado y olía a cebolla y a papel.", "L'aria era pesante e sapeva di cipolla e di carta."],
   ["Elena abrió la puerta del todo para que entrara luz.", "Elena aprì la porta del tutto per far entrare luce."],
   ["La luz no ayudó mucho, pero ayudó algo.", "La luce non aiutò molto, ma qualcosa aiutò."],
  ],
  [
   ["Sobre el escritorio había dos tazas de café.", "Sulla scrivania c'erano due tazze di caffè."],
   ["Una estaba vacía.", "Una era vuota."],
   ["La otra estaba llena hasta la mitad.", "L'altra era piena a metà."],
   ["Elena tocó las dos con el dorso de la mano.", "Elena toccò entrambe con il dorso della mano."],
   ["Las dos estaban frías.", "Erano entrambe fredde."],
   ["—Vino alguien —dijo Beltrán—. Tomaron café juntos.", "«È venuto qualcuno», disse Beltrán. «Hanno preso il caffè insieme»."],
  ],
  [
   ["El socio del gerente se llamaba Julián Robles.", "Il socio del direttore si chiamava Julián Robles."],
   ["Llegó a mediodía, pálido y hablando mucho.", "Arrivò a mezzogiorno, pallido e parlando molto."],
   ["—Estuve aquí anoche hasta las nueve —dijo—.", "«Sono stato qui ieri sera fino alle nove», disse."],
   ["—Tomamos un café y me fui.", "«Abbiamo preso un caffè e me ne sono andato»."],
   ["—Él se quedó a revisar las cuentas.", "«Lui è rimasto a controllare i conti»."],
   ["Elena escuchó sin interrumpir.", "Elena ascoltò senza interrompere."],
  ],
  [
   ["Después fue a la cocina y buscó la cafetera.", "Poi andò in cucina e cercò la caffettiera."],
   ["Estaba limpia y guardada en su lugar.", "Era pulita e riposta al suo posto."],
   ["Preguntó a la cocinera quién hacía el café.", "Chiese alla cuoca chi facesse il caffè."],
   ["—Yo, siempre —dijo la mujer—. En la mañana.", "«Io, sempre», disse la donna. «La mattina»."],
   ["—¿Y en la noche?", "«E la sera?»"],
   ["—En la noche nadie. La cafetera se apaga a las seis.", "«La sera nessuno. La caffettiera si spegne alle sei»."],
  ],
  [
   ["Elena volvió a la oficina y miró las tazas otra vez.", "Elena tornò in ufficio e guardò di nuovo le tazze."],
   ["La taza llena hasta la mitad tenía una marca en el borde.", "La tazza piena a metà aveva un segno sul bordo."],
   ["Una línea seca, de café, un poco más abajo del líquido.", "Una riga secca, di caffè, un po' più in basso del liquido."],
   ["—Beltrán, mire esto.", "«Beltrán, guardi questo»."],
   ["—Alguien bebió de esta taza y después la volvió a llenar.", "«Qualcuno ha bevuto da questa tazza e poi l'ha riempita di nuovo»."],
  ],
  [
   ["Elena salió al patio y se quedó un momento en la sombra.", "Elena uscì nel cortile e rimase un momento all'ombra."],
   ["Un gato flaco la miró desde la barda y se fue.", "Un gatto magro la guardò dal muretto e se ne andò."],
   ["Pensó que casi todos los asesinatos son torpes.", "Pensò che quasi tutti gli omicidi sono goffi."],
   ["La gente inventa una escena y se olvida de la cocina.", "La gente inventa una scena e si dimentica della cucina."],
   ["Siempre se olvidan de la cocina.", "Si dimenticano sempre della cucina."],
  ],
  [
   ["Julián insistió en que se había ido a las nueve.", "Julián insistette che se n'era andato alle nove."],
   ["Elena le preguntó de dónde había salido el café.", "Elena gli chiese da dove fosse uscito il caffè."],
   ["Él dijo que lo había hecho el gerente.", "Lui disse che l'aveva fatto il direttore."],
   ["Ella le explicó lo de la cafetera.", "Lei gli spiegò la faccenda della caffettiera."],
   ["Le explicó que el café de esas tazas era de la mañana.", "Gli spiegò che il caffè di quelle tazze era della mattina."],
   ["De esa mañana.", "Di quella mattina."],
  ],
  [
   ["—Usted volvió hoy temprano —dijo—.", "«Lei è tornato stamattina presto», disse."],
   ["—Hizo café para dos y dejó las tazas.", "«Ha fatto il caffè per due e ha lasciato le tazze»."],
   ["—Quería que pensáramos en una visita de anoche.", "«Voleva che pensassimo a una visita di ieri sera»."],
   ["—Pero la cocinera apaga la cafetera a las seis.", "«Ma la cuoca spegne la caffettiera alle sei»."],
   ["—Y usted no lo sabía, porque usted nunca entra a la cocina.", "«E lei non lo sapeva, perché lei in cucina non ci entra mai»."],
   ["Julián se sentó despacio en la silla del gerente.", "Julián si sedette lentamente sulla sedia del direttore."],
   ["Fue lo único honesto que hizo en todo el día.", "Fu l'unica cosa onesta che fece in tutta la giornata."],
  ],
 ],
},
]
